version: '3.8' # 스웜 모드 버전을 명시

services:
  # --- 1. MongoDB (Data Tier) ---
  mongodb:
    image: mongo:4
    volumes: 
      - mongodb-db:/data/db 
    deploy:
      replicas: 1 # 단일 인스턴스 유지
      resources: # <--- 리소스 추가
        limits:
          cpus: '1.0'
          memory: 1G
      placement:
        constraints:
          - node.role == manager # 매니저 노드에 배치
    ports:
      - "27017:27017" # 필요시 외부 접근 포트 노출
    networks:
      - back_net # 전용 네트워크 사용

  # --- 2. Backend (API Tier) ---
  backend:
    image: harbor.local.net/myproject/backend:2.0_slim
    environment:
      - PORT=8000
      - GUESTBOOK_DB_ADDR=mongodb:27017 
    deploy:
      replicas: 3 
      resources: # <--- 리소스 추가
        limits:
          cpus: '0.5' # 이미지 0.5(50%)
          memory: 256M
      placement:
        constraints:
          - node.role == worker 
    networks:
      - back_net

  # --- 3. HAProxy (Internal Load Balancer) ---
  haproxy_core:
    image: harbor.local.net/myproject/haproxy:2.0
    deploy:
      replicas: 1
      resources: # <--- 리소스 추가
        limits:
          cpus: '0.1'
          memory: 128M
    networks:
      - back_net # Backend와 Frontend 모두와 통신하기 위한 네트워크

  # --- 4. Frontend (App Tier) ---
  project_frontend:
    image: harbor.local.net/myproject/frontend:2.0_slim
    environment:
      - PORT=8000
      - GUESTBOOK_API_ADDR=haproxy_core:80 # 서비스 이름으로 HAProxy 접근
    deploy:
      replicas: 3 # 3개 복제본 유지
      resources: # <--- 리소스 추가
        limits:
          cpus: '0.25'
          memory: 128M
      placement:
        constraints:
          - node.role == worker # 워커 노드에 배치
    networks:
      - web_net
      - back_net

  # --- 5. Nginx (Edge Proxy / Web Load Balancer) ---
  web_proxy:
    image: harbor.local.net/myproject/nginx_proxy:2.0
    ports:
      - "8888:80" # 외부 접속 포트 노출
    deploy:
      replicas: 1 
      resources: # <--- 리소스 추가
        limits:
          cpus: '0.1'
          memory: 128M
      placement:
        constraints:
          - node.role == worker # 워커 노드에 배치
    networks:
      - web_net # Frontend와 연결

# --- 네트워크 정의 (Overlay로 전환) ---
networks:
  back_net: # Backend <-> MongoDB
    driver: overlay
  web_net:  # Frontend <-> Nginx
    driver: overlay

# --- 볼륨 정의 ---
volumes:
  mongodb-db:
    driver: local