services:
  proxy:
    image: jwilder/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - webnet

  backend:
    build: .
    expose:
      - "5000"
    volumes:
      - .:/code
    environment:
      - VIRTUAL_HOST=192.168.56.101
      - VIRTUAL_PORT=5000
    depends_on:
      - redis
    networks:
      - webnet

  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - webnet
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}
networks:
  webnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1
