services:
  nginx:
    image: nginx:1.25.4-alpine
    deploy:
      replicas: 4
      placement:
        constraints:
          - node.role != manager
      restart_policy:
        condition: on-failure
        max_attempts: 3
    environment:
      - SERVICE_PORTS=80
    networks:
      - haproxy-web
  proxy:
    image: dbgurum/haproxy:1.0
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
    networks:
      - haproxy-web
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

networks:
  haproxy-web:
      external: true